# minikube tunnel
# kubectl apply -f service.yaml 
# kubectl get services -n development
# http://127.0.0.1 [external ip]
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: development
spec:
  selector:
    app: pod-info
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
